<div class="tab-pane" id="tab5">
              <fieldset>
                <legend>¿Por qué quieres trabajar en <span class="upper">CEMACO</span>?</legend>
                <div class="row-fluid">
                  <div class="span12">
                    <textarea class="span12" maxlength="254" rows="3" minlength="10" name="" ></textarea>
                  </div>
                </div>
              </fieldset>
              <br/>
              <hr>

              <fieldset>
                <legend>¿Qué persona, en el pasado, te gustaría conocer?</legend>
                <div class="row-fluid">
                  <div class="span12">
                    <textarea class="span12 textLimiter" rows="3" maxlength="254" minlength="5" name=""></textarea>
                  </div>
                </div>
                <legend>¿Porque?</legend>
                <div class="row-fluid">
                  <div class="span12">
                    <textarea class="span12 textLimiter" rows="3" maxlength="254" minlength="5" name=""></textarea>
                  </div>
                </div>
              </fieldset>
              <br/>
              <hr>


        </div>
        <input name="idOferenteUsuario" value="" type="hidden" />
        <input type="hidden" name="sheet" id="sheet" value="1" />


