<?php
$usuario = get_current_user_id();
// Obtiene datos guardados en la db
$estudios =  $wpdb->get_results( "SELECT * FROM gc_usuarios_estudios WHERE UserId=$usuario" );
$cursos =  $wpdb->get_results( "SELECT * FROM gc_usuarios_estudios_cursos WHERE UserId=$usuario" );
$idiomas =  $wpdb->get_results( "SELECT * FROM gc_usuarios_estudios_idioma WHERE UserId=$usuario" );
$idiomasSiNo =  $wpdb->get_results( "SELECT * FROM gc_usuarios_estudios_idioma WHERE UserId=$usuario LIMIT 1" );

$titulo =  $wpdb->get_results( "SELECT e_Titulo FROM gc_usuarios_estudios WHERE UserId=$usuario" );

// Obtiene listas creadas de la db
$paises =  $wpdb->get_results( "SELECT Codigo, Pais FROM gc_info_paises" );
$deptos =  $wpdb->get_results( "SELECT Codigo, Descripcion FROM gc_info_departamentos" );
$municipios =  $wpdb->get_results( "SELECT Codigo, Descripcion FROM gc_info_municipios" );
?>

<div class="tab-pane" id="tab2">

      <legend>Agrega tu información académica desde la más reciente hasta la más antigua</legend>
      <?php
      $userEst = (is_array($estudios)&&count($estudios)>0?$estudios:array(0=>array()));
      $i=0;
      foreach($userEst as $index => $estudio){ ?>
      <fieldset class="oferente-estudios">
        <div class="row-fluid">
        <div class="span1 text-center"><br />
          <i class="icon-folder-open"></i> </div>
        <div class="span11">
          <div class="section">
            <legend class="legend-curso">&nbsp;
              <!-- <a href="javascript:void(0)" class="pull-right btn btn-danger btn-mini delete_estudio" data-toggle="popover" tabindex="-1" data-placement="right" title="Click aquí para eliminar esta estudio" style="padding: 0 0 0 3px;">
                <i class="icon-trash icon-white"></i> &nbsp;
              </a> -->
            </legend>
            <div class="row-fluid fCarreras">
              <div class="span4">
                <label> Título o Diploma Obtenido </label>
                <input class="span12" type="text" maxlength="90" name="titulo[]" value="<?php echo $estudio->e_Titulo ?>" />
              </div>
              <div class="span4">
                <?php $nivelEstudios = $estudio->e_NivelEstudios ?>
                <label> Nivel de estudios </label>
                <select name="nivelEstudios[]" class="span12">
                  <option value="Primaria" <?php echo ($nivelEstudios=='Primaria'?'selected="selected"':'')  ?>>Primaria</option>
                  <option value="Basicos" <?php echo ($nivelEstudios=='Basicos'?'selected="selected"':'')  ?>>Básicos</option>
                  <option value="Diversificado" <?php echo ($nivelEstudios=='Diversificado'?'selected="selected"':'')  ?>>Diversificado</option>
                  <option value="Tecnico" <?php echo ($nivelEstudios=='Tecnico'?'selected="selected"':'')  ?>>Técnico</option>
                  <option value="Postgrado" <?php echo ($nivelEstudios=='Postgrado'?'selected="selected"':'')  ?>>Postgrado (Maestría, Especialización, Doctorado)</option>
                  <option value="Licenciatura" <?php echo ($nivelEstudios=='Licenciatura'?'selected="selected"':'')  ?>>Licenciatura</option>
                </select>
              </div>
              <div class="span4">
                <label> Nombre del Centro de Estudios </label>
                <input class="span12" maxlength="100" type="text" name="nombreCentroEstudios[]" value="<?php echo $estudio->e_NombreCentroEstudios ?>" />
              </div>
            </div>
            <div class="row-fluid dateRanges">
              <div class="span4">
                <?php $paisEstudios = $estudio->e_PaisCentroEstudios ?>
                <label> * País </label>
                <select class="span15 required-send oedPais" name="pais[]">
                  <option value="0">-- País --</option>
                  <?php foreach ($paises as $pais): ?>
                    <option value="<?php echo $pais->Codigo ?>" <?php echo ($paisEstudios==$pais->Codigo?'selected="selected"':'')  ?>><?php echo $pais->Pais ?></option>
                  <?php endforeach; ?>
                </select>
              </div>
              <div class="span3">
                <label><span>Fecha de Inicio</span></label>
                <input class="span12 require dateITA dateMin" maxlength="10" type="text" name="fechaInicio[]" value="<?php echo $estudio->e_FechaInicio ?>" />
              </div>
              <div class="span3 dateRange">
                <label> Fecha Final </label>
                <label class="checkbox inline">
                  <input class="estudioFechaFinal" name="hastaLaFecha[]" type="checkbox" value="hasta_fecha" <?php if($estudio->e_HastaLaFecha=='hasta_fecha'):?>checked="checked"<?php endif; ?>/>
                  Hasta la Fecha
                </label>
                <input class="span12 dateITA dateMax finalDate" maxlength="10" type="text" name="fechaFinal[]" value="<?php echo $estudio->e_FechaFinal ?>" <?php if($estudio->e_HastaLaFecha=='hasta_fecha'):?>style="display:none;"<?php endif; ?>/>
              </div>
              <div class="span2">
                <?php $estadoEstudios = $estudio->e_Estado ?>
                <label> Estado </label>
                <select class="span12 " name="estado[]" >
                  <option value="En curso" <?php echo ($estadoEstudios=='En curso'?'selected="selected"':'')  ?>>En curso</option>
                  <option value="Abandonado" <?php echo ($estadoEstudios=='Abandonado'?'selected="selected"':'')  ?>>Abandonado</option>
                  <option value="Graduado" <?php echo ($estadoEstudios=='Graduado'?'selected="selected"':'')  ?>>Graduado</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </fieldset>
      <?php } ?>

      <div class="span10 text-center">
        <a href="javascript:void(0)" id="addEstudio" class="btn btn-primary"><i class="icon-chevron-down icon-white"></i> Agregar Estudio</a>
      </div>

      <br><br>


        <legend>Conocimientos y Cursos</legend>
        <em>Agrega los conocimientos y cursos que te ayudan a calificar para el puesto</em>
        <?php
        $userCur = (is_array($cursos)&&count($cursos)>0?$cursos:array(0=>array()));
        $i=0;
        foreach($userCur as $index => $curso){ ?>
        <fieldset class="cursos-maquinaria">
          <div class="row-fluid">
            <div class="span1 text-center"><br />
              <i class="icon-folder-open"></i> </div>
            <div class="span11">
              <div class="section">
                <legend class="legend-curso" style="width: 95%;">&nbsp;</legend>
                <div class="row-fluid">
                  <div class="span6">
                    <label><span>Nombre del Conocimiento/Curso</span> </label>
                    <input maxlength="100" class="span11 require" type="text" name="conocimientoNombre[]" value="<?php echo $curso->ec_NombreCursoOConocimiento?>"/>
                  </div>
                  <div class="span6">
                    <?php $nivelCurso = $curso->ec_Nivel ?>
                    <label>Nivel</label>
                    <select name="conocimientoNivel[]" class="span11">
                      <option value="basico" <?php echo ($nivelCurso=='basico'?'selected="selected"':'')  ?>>Básico</option>
                      <option value="intermedio" <?php echo ($nivelCurso=='intermedio'?'selected="selected"':'')  ?>>Intermedio</option>
                      <option value="avanzado" <?php echo ($nivelCurso=='avanzado'?'selected="selected"':'')  ?>>Avanzado</option>
                    </select>
                  </div>
                </div>
                <div class="row-fluid">
                  <div class="span12">
                    <label><span>Descripción </span> </label>
                    <input maxlength="100" class="span12 require" type="text" name="conocimientoDescripcion[]" style="width: 96%;" value="<?php echo $curso->ec_Descripcion?>"/>
                  </div>
                </div>

              </div>
            </div>
          </div>
      </fieldset>
      <?php } ?>

      <div class="span10 text-center">
        <a href="javascript:void(0)" id="addCursoMaquinaria"  class="btn btn-primary"> <i class="icon-chevron-down icon-white"></i>Agregar Conocimiento/ Curso</a>
      </div>
      <br><br>

      <fieldset>
        <legend>¿Dominas algún idioma adicional al español?</legend>
        <div class="section">
        <div class="row-fluid">
          <div class="span5">
            <?php $userIdioma = (is_array($idiomasSiNo)&&count($idiomasSiNo)>0?$idiomasSiNo:array(0=>array())); foreach($userIdioma as $index => $idioma){ ?>
              <?php $dominas = $idioma->ei_DominasIdioma ?>
              <select class="span12 onoff" name="idiomaSiNo[]">
                <option value="S" <?php echo ($dominas=='S'?'selected="selected"':'') ?>>Sí</option>
                <option value="N" <?php echo ($dominas=='N'?'selected="selected"':'') ?>>No</option>
              </select>
            <?php } ?>
          </div>
        </div><br>
        <div class="row-fluid">
          <div class="span12">
            <?php
            $i=0;
            $userIdioma = (is_array($idiomas)&&count($idiomas)>0?$idiomas:array(0=>array()));
            foreach($userIdioma as $index => $idioma){ ?>
            <fieldset class="idiomas">
              <div class="row-fluid"> <span class="span12"> <span class="span5">
                <input class="span12" maxlength="25" type="text" value="<?php echo $idioma->ei_TipoIdioma ?>" name="idiomaNombre[]" placeholder="Idioma" style="margin-bottom: 3px;"/>
                </span>
                <span class="span5" style="margin: 0">
                <table border="1px" cellpadding="7px" class="span12">
                  <tr>
                    <td>Lectura</td>
                    <td>Escritura</td>
                    <td>Conversacion</td>
                  </tr>
                  <tr>
                    <td>
                      <?php $lectura = $idioma->ei_NivelLeido ?>
                      <select name="lectura[]" id="" class="span12">
                        <option value="">-- Nivel --</option>
                        <option value="Bajo" <?php echo ($lectura=='Bajo'?'selected="selected"':'') ?>>Bajo</option>
                        <option value="Intermedio" <?php echo ($lectura=='Intermedio'?'selected="selected"':'') ?>>Intermedio</option>
                        <option value="Avanzado" <?php echo ($lectura=='Avanzado'?'selected="selected"':'') ?>>Avanzado</option>
                      </select>
                    </td>
                    <td>
                      <?php $escritura = $idioma->ei_NivelEscrito ?>
                      <select name="escritura[]" id="" class="span12">
                        <option value="">-- Nivel --</option>
                        <option value="Bajo" <?php echo ($escritura=='Bajo'?'selected="selected"':'') ?>>Bajo</option>
                        <option value="Intermedio" <?php echo ($escritura=='Intermedio'?'selected="selected"':'') ?>>Intermedio</option>
                        <option value="Avanzado" <?php echo ($escritura=='Avanzado'?'selected="selected"':'') ?>>Avanzado</option>
                      </select>
                    </td>
                    <td>
                      <?php $conversacion = $idioma->ei_NivelConversacion ?>
                      <select name="conversacion[]" id="" class="span12">
                        <option value="">-- Nivel --</option>
                        <option value="Bajo" <?php echo ($conversacion=='Bajo'?'selected="selected"':'') ?>>Bajo</option>
                        <option value="Intermedio" <?php echo ($conversacion=='Intermedio'?'selected="selected"':'') ?>>Intermedio</option>
                        <option value="Avanzado" <?php echo ($conversacion=='Avanzado'?'selected="selected"':'') ?>>Avanzado</option>
                      </select>
                    </td>
                  </tr>
                </table>
                </span>
                </div>

                <span class="span2" style="margin: -10px;"></span> </span>
            </fieldset>
            <?php } ?>
          </div>
        </div>
        </div>
      </fieldset>

      <div class="row-fluid">
        <div class="span12 text-center">
          <a href="javascript:void(0)" class="btn btn-primary clone" data-index="3" type="button" id="addOtroIdioma">
            <i class="icon-chevron-down icon-white"></i> Agregar Otro Idioma</a>
          </div>
      </div>


</div>
