<?php
$usuario = get_current_user_id();
// Obtiene datos guardados en la db
$primerNombre =  $wpdb->get_var( "SELECT s_PrimerNombre FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$segundoNombre =  $wpdb->get_var( "SELECT s_SegundoNombre FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$primerApellido =  $wpdb->get_var( "SELECT s_PrimerApellido FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$segundoApellido =  $wpdb->get_var( "SELECT s_SegundoApellido FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$apellidoCasada =  $wpdb->get_var( "SELECT s_ApellidoCasada FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$paisNac =  $wpdb->get_var( "SELECT s_PaisNacimiento FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$departamentoNac =  $wpdb->get_var( "SELECT s_DepartamentoNacimiento FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$municipioNac =  $wpdb->get_var( "SELECT s_MunicipioNacimiento FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$fechaNac =  $wpdb->get_var( "SELECT s_FechaNacimiento FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$direccion =  $wpdb->get_var( "SELECT s_Direccion FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$telefono =  $wpdb->get_var( "SELECT s_Telefono FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$celular =  $wpdb->get_var( "SELECT s_Celular FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$colonia =  $wpdb->get_var( "SELECT s_ColonaDireccion FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$zona =  $wpdb->get_var( "SELECT s_ZonaDireccion FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$paisDirec =  $wpdb->get_var( "SELECT s_PaisDireccion FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$deptoDirec =  $wpdb->get_var( "SELECT s_DepartamentoDireccion FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$munDirec =  $wpdb->get_var( "SELECT s_MunicipioDireccion FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$identificacion =  $wpdb->get_var( "SELECT s_NumeroIdentificacion FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );

$tipoDocumento =  $wpdb->get_var( "SELECT s_DocumentoIdentificacion FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );

$paisExtendido =  $wpdb->get_var( "SELECT s_ExtendidoEnPais FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$deptoExtendido =  $wpdb->get_var( "SELECT s_ExtendidoEnDepartamento FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );
$munExtendido =  $wpdb->get_var( "SELECT s_ExtendidoEnMunicipio FROM gc_usuarios_sobreTi WHERE UserId=$usuario LIMIT 1" );


// Obtiene listas creadas de la db
$paisNacimiento =  $wpdb->get_results( "SELECT Codigo, Pais FROM gc_info_paises" );
$deptoNacimiento =  $wpdb->get_results( "SELECT Codigo, Descripcion FROM gc_info_departamentos" );
$munNacimiento =  $wpdb->get_results( "SELECT Codigo, Descripcion FROM gc_info_municipios" );
$nacionalidadNac =  $wpdb->get_results( "SELECT Codigo, Nacionalidad FROM gc_info_paises" );
?>
<div class="tab-pane active" id="tab1">
<div class="row-fluid">
  <div class="span12">

      <div class="section">
        <fieldset>
          <div class="row-fluid">
            <div class="span2">
              <label> <i class="required">* </i>Primer Nombre</label>
              <input class="span12 required-send" maxlength="20" minlength="2" required="required" name="PrimerNombre" type="text" value="<?php echo "{$primerNombre}" ?>" />
            </div>
            <div class="span2">
              <label>Segundo Nombre</label>
              <input class="span12" maxlength="20" minlength="2" name="SegundoNombre" value="<?php echo "{$segundoNombre}" ?>" type="text" />
            </div>
            <div class="span2">
              <label> <i class="">* </i>Primer Apellido</label>
              <input class="span12 required-send" maxlength="20" minlength="2" required="required" name="PrimerApellido" value="<?php echo "{$primerApellido}" ?>" type="text" />
            </div>
            <div class="span2">
              <label>Segundo Apellido</label>
              <input class="span12" maxlength="20" minlength="2" name="SegundoApellido" value="<?php echo "{$segundoApellido}" ?>" type="text" />
            </div>
            <div class="span3">
              <label>Apellido de Casada</label>
              <input class="span12" maxlength="20" minlegth="2" name="ApellidoCasada" value="<?php echo "{$apellidoCasada}" ?>" type="text" />
            </div>
          </div>
        </fieldset>
      </div>
      <div class="section">
        <fieldset>
          <label>Lugar de Nacimiento</label>
          <div class="row-fluid">
            <div class="span4">
              <select class="span12 cctld pais-nacimiento" name="PaisNacimiento">
                <option value="0">-- País --</option>
                <?php foreach ($paisNacimiento as $pais) { ?>
                 <option value="<?php echo $pais->Codigo; ?>" <?php echo((int) $pais->Codigo == (int) $paisNac?'selected="selected"':'')?>><?php echo $pais->Pais; ?></option>
                <?php } ?>
              </select>
            </div>
            <div class="span4">
              <select class="span12 depto -send" name="DepartamentoNacimiento" data-transfer="Oferentes[idMunicipioNacimiento]">
                <option value="">-- Departamento --</option>
                <?php foreach ($deptoNacimiento as $depto) { ?>
                 <option value="<?php echo $depto->Codigo; ?>" <?php echo((int) $depto->Codigo == (int) $departamentoNac?'selected="selected"':'')?>><?php echo $depto->Descripcion; ?></option>
                <?php } ?>
              </select>
            </div>
            <div class="span4">
              <select class="muni -send span12" name="MunicipioNacimiento">
                <option value="">-- Municipio --</option>
                <?php foreach ($munNacimiento as $mun) { ?>
                 <option value="<?php echo $mun->Codigo; ?>" <?php echo((int) $mun->Codigo == (int) $municipioNac?'selected="selected"':'')?>><?php echo $mun->Descripcion; ?></option>
                <?php } ?>
              </select>
            </div>
          </div>
        </fieldset>
        <fieldset>
          <label>Nacionalidad</label>
          <div class="row-fluid">
            <div class="span12">
              <select class="span4 pais-nacimiento" name="nacionalidad" readonly="readonly" disabled>
                <option value="" selected="selected">-- Nacionalidad --</option>
                <?php foreach ($nacionalidadNac as $nacionalidad) { ?>
                 <option value="<?php echo $nacionalidad->Codigo; ?>" <?php echo((int) $nacionalidad->Codigo == (int) $paisNac?'selected="selected"':'')?>><?php echo $nacionalidad->Nacionalidad; ?></option>
                <?php } ?>
              </select>
            </div>
          </div>
        </fieldset>
      </div>
      <div class="section">
        <fieldset>
          <div class="row-fluid">
            <div class="span4">
              <label><i class="required">* </i>Fecha de Nacimiento</label>
              <div>
                <?php
                  list($year, $month, $day) = explode('-', $fechaNac);
                ?>
                <select class="span3 required-send" name="DiaNacimiento" required="required" >
                  <option value="">Día</option>
                  <?php for($i=1;$i<=31;$i++) echo '<option value="'.$i.'" '.($day==$i?'selected="selected"':'').'>'.$i.'</option>'; ?>
                </select>
                <select class="span3 required-send" name="MesNacimiento" required="required" >
                  <option value="">Mes</option>
                  <?php for($i=1;$i<=12;$i++) echo '<option value="'.$i.'" '.($month==$i?'selected="selected"':'').'>'.$i.'</option>'; ?>
                </select>
                <select class="span4 required-send" name="AnioNacimiento" required="required" >
                  <option value="">A&ntilde;o</option>
                  <?php for($i=(new DateTime('now - 60 year'))->format('Y'), $today=date('Y');$i<=$today;$i++) echo '<option value="'.$i.'"  '.($year==$i?'selected="selected"':'').'>'.$i.'</option>'; ?>
                </select>
              </div>
            </div>
            <div class="span3">
              <label>Estado Civil</label>
              <select class="span12 " name="Oferentes[oEstadoCivil]">
                <option value="">---SELECCIONAR---</option>
              </select>
            </div>
            <div class="span3">
              <label>Sexo</label>
              <select class="span12 genre " name="Oferentes[oSexo]">
                <option value="">---SELECCIONAR---</option>
              </select>
            </div>
          </div>
        </fieldset>
      </div>
      <div class="section">
        <fieldset>
          <div class="row-fluid">
            <div class="span4">
              <label><i class="required">* </i>Dirección Actual</label>
              <input class="span12 addr required-send" type="text" maxlength="100" minlength="5" required="required" name="Direccion" id="direccion-actual" value="<?php echo "{$direccion}" ?>"/>
            </div>
            <div class="span3">
              <label>Colonia</label>
              <input class="span12" maxlength="50" name="Colonia" type="text" value="<?php echo "{$colonia}" ?>" />
            </div>
            <div class="span1">
              <label>Zona</label>
              <input class="span12 integer" maxlength="2" minlength="1" name="Zona" type="text" value="<?php echo "{$zona}" ?>" />
            </div>
          </div>
          <div class="row-fluid">
            <div class="span4">
              <select class="span12 cctld required-send" name="PaisDireccion">
                <option value="0">-- País --</option>
                <?php foreach ($paisNacimiento as $pais) { ?>
                 <option value="<?php echo $pais->Codigo; ?>" <?php echo((int) $pais->Codigo == (int) $paisDirec?'selected="selected"':'')?>><?php echo $pais->Pais; ?></option>
                <?php } ?>
              </select>
            </div>
            <div class="span4">
              <select class="span12  depto required-send" name="DeptoDireccion" data-transfer="Oferentes[idMunicipioDireccion]">
                <option value="">-- Departamento --</option>
                <?php foreach ($deptoNacimiento as $depto) { ?>
                 <option value="<?php echo $depto->Codigo; ?>" <?php echo((int) $depto->Codigo == (int) $deptoDirec?'selected="selected"':'')?>><?php echo $depto->Descripcion; ?></option>
                <?php } ?>
              </select>
            </div>
            <div class="span4">
              <select class=" muni span12 required-send" name="MunicipioDireccion">
                <option value="">-- Municipio --</option>
                <?php foreach ($munNacimiento as $mun) { ?>
                 <option value="<?php echo $mun->Codigo; ?>" <?php echo((int) $mun->Codigo == (int) $munDirec?'selected="selected"':'')?>><?php echo $mun->Descripcion; ?></option>
                <?php } ?>
              </select>
            </div>
          </div>
        </fieldset>
      </div>
      <div class="section">
        <fieldset>
          <div class="row-fluid">
            <div class="span4">
              <label> Teléfono de Casa </label>
              <input class="span12 phoneGT integer" maxlength="8" minlength="8"  onkeypress='return event.charCode >= 48 && event.charCode <= 57' name="Telefono" value="<?php echo "{$telefono}" ?>" type="text" />
            </div>
            <div class="span4">
              <label> <i class="required">* </i>Celular</label>
              <input class="span12 phoneGT integer required-send" maxlength="8" minlength="8"  onkeypress='return event.charCode >= 48 && event.charCode <= 57'  required="required" name="Celular" type="text" value="<?php echo "{$celular}" ?>" />
            </div>
          </div>
        </fieldset>
      </div>
      <div class="section">
        <fieldset>
          <div class="row-fluid">
            <div class="span4">
              <label> <i class="required">* </i>Documento de Identificación</label>
              <select class="span12 required-send" name="tipoDocomento">
                <option value="">-- Selecionar --</option>
                <option value="Pasaporte" <?php echo($tipoDocumento=='Pasaporte'?'selected="selected"':'') ?>>Pasaporte</option>
                <option value="DPI" <?php echo($tipoDocumento=='DPI'?'selected="selected"':'') ?>>DPI</option>
              </select>
            </div>
            <div class="span4">
              <label> <i class="required">* </i>Número de Identificación</label>
              <input class="span8 digits required-send" maxlength="20" required="required" type="text" name="NumeroIdentificacion" value="<?php echo "{$identificacion}" ?>" />
            </div>
          </div>
          <div class="row-fluid">
            <div class="span7">
              <label><i class="required">* </i>Extendido en </label>
              <div class="row-fluid">
                <div class="span4">
                  <select id="country_passport" class="span12 cctld notZero required-send select2" required="required" name="PaisExtendidoEn" >
                    <option value="">-- País --</option>
                    <?php foreach ($paisNacimiento as $pais) { ?>
                     <option value="<?php echo $pais->Codigo; ?>" <?php echo((int) $pais->Codigo == (int) $paisExtendido?'selected="selected"':'')?>><?php echo $pais->Pais; ?></option>
                    <?php } ?>
                  </select>
                </div>

                <div class="span4">
                  <select class="span12 depto required-send" name="DepartamentoExtendidoEn" data-transfer="MunicipioExtendidoEn">
                    <option value="">-- Departamento --</option>
                    <?php foreach ($deptoNacimiento as $depto) { ?>
                     <option value="<?php echo $depto->Codigo; ?>" <?php echo((int) $depto->Codigo == (int) $deptoExtendido?'selected="selected"':'')?>><?php echo $depto->Descripcion; ?></option>
                    <?php } ?>
                  </select>
                </div>

                <div class="span4">
                  <select class="span12 muni required-send" name="MunicipioExtendidoEn">                </div>

                    <option value="">-- Municipio --</option>
                    <?php foreach ($munNacimiento as $mun) { ?>
                     <option value="<?php echo $mun->Codigo; ?>" <?php echo((int) $mun->Codigo == (int) $munExtendido?'selected="selected"':'')?>><?php echo $mun->Descripcion; ?></option>
                    <?php } ?>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </fieldset>
      </div>



  </div>
</div>
</div>
