<div class="tab-pane" id="tab2">
  <div class="btn-group padtop1 pull-right">
  	<a class="btn btn-mini btn-next" url="">
  	<span>Guardar</span></a>

  	<a class="btn btn-mini btn-prev" data-toggle="tab" href="#tab1">
  	<span>&lsaquo; Anterior</span> </a>

  	<a class="btn btn-mini btn-next" data-toggle="tab" href="#tab3" url="">
  	<span>Siguiente &rsaquo;</span> </a>
  </div>

      <h2>¿Qué has estudiado?</h2>
      <legend>Agrega tu información académica desde la más reciente hasta la más antigua</legend>
      <fieldset class="oferente-estudios">
        <div class="row-fluid">
        <div class="span1 text-center"><br />
          <i class="icon-folder-open"></i> </div>
        <div class="span11">
          <div class="section">
            <legend class="legend-curso">&nbsp;
              <!-- <a href="javascript:void(0)" class="pull-right btn btn-danger btn-mini delete_estudio" data-toggle="popover" tabindex="-1" data-placement="right" title="Click aquí para eliminar esta estudio" style="padding: 0 0 0 3px;">
                <i class="icon-trash icon-white"></i> &nbsp;
              </a> -->
            </legend>
            <div class="row-fluid fCarreras">
              <div class="span4">
                <label> Título o Diploma Obtenido </label>
                <input class="span12" type="text" maxlength="90" name="OferenteEducacion[][oedTituloObtenido]" value="" />
              </div>
              <div class="span4">
                <label> Nivel de estudios </label>
                <select name="OferenteEducacion[][oedUltimoGradoAprobado]" class="span12">
                  <option value="Primaria">Primaria</option>
                  <option value="Basicos">Básicos</option>
                  <option value="Diversificado">Diversificado</option>
                  <option value="Tecnico">Técnico</option>
                  <option value="Postgrado">Postgrado (Maestría, Especialización, Doctorado)</option>
                  <option value="Licenciatura">Licenciatura</option>
                </select>
              </div>
              <div class="span4">
                <label> Nombre del Centro de Estudios </label>
                <input class="span12" maxlength="100"   type="text" name="OferenteEducacion[][oedInstitucion]" value="" />
              </div>
            </div>
            <div class="row-fluid dateRanges">
              <div class="span4">
                <label> * País </label>
                <select class="span15 required-send oedPais" name="OferenteEducacion[][oedPais]">
                  <option value="0">-- País --</option>
                </select>
              </div>
              <div class="span3">
                <label><span>Fecha de Inicio</span></label>
                <input class="span12 require dateITA dateMin" maxlength="10" type="text" name="OferenteEducacion[][oedFechaInicial]" value="" />
              </div>
              <div class="span3 dateRange">
                <label> Fecha Final </label>
                <label class="checkbox inline">
                  <input class="estudioFechaFinal" name="OferenteEducacion[][oedHastaLaFecha]" type="checkbox" value="hasta_fecha" />
                  Hasta la Fecha
                </label>
                <input class="span12 dateITA dateMax finalDate" maxlength="10" type="text" name="OferenteEducacion[][oedFechaFinal]" value=""/>
              </div>
              <div class="span2">
                <label> Estado </label>
                <select class="span12 " name="OferenteEducacion[][oedEstado]" >
                  <option value="A">En curso</option>
                  <option value="I">Abandonado</option>
                  <option value="C">Graduado</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </fieldset>

      <div class="span10 text-center">
        <a href="javascript:void(0)" id="addEstudio" class="btn btn-primary"><i class="icon-chevron-down icon-white"></i> Agregar Estudio</a>
      </div>

      <br><br>

      <fieldset>
        <legend>Conocimientos y Cursos</legend>
        <em>Agrega los conocimientos y cursos que te ayudan a calificar para el puesto</em>

        <fieldset class="cursos-maquinaria">
          <div class="row-fluid">
            <div class="span1 text-center"><br />
              <i class="icon-folder-open"></i> </div>
            <div class="span11">
              <div class="section">
                <legend class="legend-curso">&nbsp;
                  <!-- <a href="javascript:void(0)" class="pull-right btn-mini btn btn-danger delete_curso" data-toggle="popover" tabindex="-1" data-placement="right" title="Click aquí para eliminar este curso" style="padding: 4px 5px 3px 3px;">
                    <i class="icon-trash icon-white"></i>
                  </a> -->
                </legend>
                <div class="row-fluid">
                  <div class="span6">
                    <label><span>Nombre del Conocimiento/Curso</span> </label>
                    <input maxlength="100" class="span12 require" type="text" name="OferenteMaquinaria[>][omTitulo]" value=""/>
                  </div>
                  <div class="span6">
                    <label>Nivel</label>
                    <select name="OferenteMaquinaria[>][omNivel]" class="span12">
                      <option value="basico">Básico</option>
                      <option value="intermedio">Intermedio</option>
                      <option value="avanzado">Avanzado</option>
                    </select>
                  </div>
                </div>
                <div class="row-fluid">
                  <div class="span12">
                    <label><span>Descripción </span> </label>
                    <input maxlength="100" class="span12 require" type="text" name="OferenteMaquinaria[>][omDescripcion]"  value=""/>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </fieldset>

        <div class="span10 text-center">
          <a href="javascript:void(0)" id="addCursoMaquinaria"  class="btn btn-primary"> <i class="icon-chevron-down icon-white"></i>Agregar Conocimiento/ Curso</a>
        </div>
        <br><br>
      </fieldset>

      <fieldset>
        <legend>¿Dominas algún idioma adicional al español?</legend>
        <div class="section">
        <div class="row-fluid">
          <div class="span4">
            <select class="span12 onoff">
              <option value="S">Sí</option>
              <option value="N">No</option>
            </select>
          </div>
        </div>
        <div class="row-fluid">
          <div class="span12">
            <fieldset class="idiomas">
              <div class="row-fluid"> <span class="span12"> <span class="span4">
                <input class="span12" maxlength="25" type="text" value="" name="OferenteIdiomas[][oidIdioma]" placeholder="Idioma" />
                </span>
                <span class="span4" style="margin: 0">
                <table border="1px" cellpadding="7px" class="span12">
                  <tr>
                    <td><b>Nivel</b></td>
                    <td>Bajo</td>
                    <td>Intermedio</td>
                    <td>Avanzado</td>
                  </tr>
                  <tr>
                    <td>Leido</td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelLeido]" value="C" />
                    </td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelLeido]" value="B" />
                    </td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelLeido]" value="A" />
                    </td>
                  </tr>
                  <tr>
                    <td>Escrito</td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelEscrito]" value="C" />
                    </td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelEscrito]" value="B" />
                    </td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelEscrito]" value="A" />
                    </td>
                  </tr>
                  <tr>
                    <td>Conversacion</td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelConversacion]" value="C" />
                    </td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelConversacion]" value="B" />
                    </td>
                    <td align=center>
                      <input type="radio" name="OferenteIdiomas[][oidNivelConversacion]" value="A" />
                    </td>
                  </tr>
                </table>
                </span>
                </div>

                <span class="span2 append">
                <!-- <a href="javascript:void(0)" class="pull-right btn btn-danger btn-mini delete_idioma" data-toggle="popover" tabindex="-1" data-placement="right" title="Click aquí para eliminar este idioma" style="padding: 0 0 0 3px;">
                  <i class="icon-trash icon-white"></i> &nbsp;
                </a> -->
                </span> </span>
            </fieldset>

          </div>
        </div>
      </fieldset>

      <div class="row-fluid">
        <div class="span12 text-center">
          <a href="javascript:void(0)" class="btn btn-primary clone" data-index="3" type="button" id="addOtroIdioma">
            <i class="icon-chevron-down icon-white"></i> Agregar Otro Idioma</a>
          </div>
      </div>


      <fieldset>
        <div class="row-fluid custom-btn">
          <div class="span12">
            <a class="btn btn-next pull-right" href="#tab2" url="">
            <span>Siguiente</span> </a>

            <a class="btn btn-next pull-right" url="/rrhh/micv/guardar">
            <span>Guardar</span></a>
  				</div>
        </div>
      </fieldset>
</div>
